env:
  requirements: '["pandas-datareader==0.9.0"]'
on:
  schedule:
    # runs at 05:00 UTC every day
    - cron:  '0 5 * * *'
jobs:
  build_report:
    runs-on: ubuntu-latest
    name: Run Datapane stock report every day at 6 am
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: datapane/build-action@v2
        with:
          script: "stocks.py"
          token: ${{ secrets.TOKEN }}
          requirements: "${{ env.requirements}}"
